"use client";

import { useRef, useEffect, useState, useCallback } from "react";
import { gsap, SplitText } from "@/lib/gsap";
import Image from "next/image";

const NFTS = [
  {
    id: "01",
    title: "Void Protocol",
    artist: "0xNeuron",
    price: "4.20 ETH",
    edition: "1 of 1",
    tag: "Generative",
    year: new Date().getFullYear(),
    img: "/nft1.webp",
    desc: `A recursive descent into machine consciousness — Void Protocol is a fully on-chain generative artwork born from 847 iterations of a custom noise algorithm trained on deep-sea bioluminescence data. Each pixel is a decision made by a system that learned to dream. The piece exists simultaneously as code, image, and philosophical statement: what does it mean to create without intent? The contract address is the artist. The blockchain is the canvas. Ownership is not possession — it is participation in an ongoing computational ritual that will outlive every human who has ever touched it. The work has been verified by three independent cryptographers and exists in a state of perpetual, irreversible becoming.`,
    provenance: "Minted on Ethereum mainnet · Block #19,847,221",
  },
  {
    id: "02",
    title: "Chromatic Decay",
    artist: "Lena Voss",
    price: "2.85 ETH",
    edition: "3 of 10",
    tag: "Photography",
    year: "2023",
    img: "/nft2.webp",
    desc: `Shot over 14 months across six continents, Chromatic Decay documents the slow dissolution of man-made color in natural environments — faded murals swallowed by vines, rusted signage bleeding into concrete, neon tubes flickering their last photons into empty streets at 4am. Voss developed a custom film emulsion that hyper-saturates decay, turning entropy into spectacle. The series asks whether beauty requires permanence, or whether the most honest art is the kind that admits it is already dying. Each edition is paired with a physical archival print, signed and numbered, shipped in a hand-welded steel case. The negative is destroyed upon sale.`,
    provenance: "Edition 3 of 10 · Authenticated by Voss Studio, Berlin",
  },
  {
    id: "03",
    title: "Neural Garden",
    artist: "Akira Moto",
    price: "7.00 ETH",
    edition: "1 of 1",
    tag: "AI × Sculpture",
    year: new Date().getFullYear(),
    img: "/nft3.webp",
    desc: `Neural Garden began as a 3D scan of Moto's grandmother's garden in Kyoto, fed into a diffusion model fine-tuned on 12th-century Heian-period ink paintings and contemporary brutalist architecture. The result is a space that could not exist — too organic to be built, too structured to be grown. The final render took 11 days on a cluster of 64 GPUs. The piece is accompanied by a 23-minute spatial audio composition generated by the same model, mapping each visual element to a frequency. To own Neural Garden is to own a place. A place that exists only because someone asked a machine to remember something it never experienced.`,
    provenance: "Unique · Accompanied by lossless audio file · Tokyo, 2024",
  },
  {
    id: "04",
    title: "The Last Signal",
    artist: "RΛVΞN",
    price: "12.5 ETH",
    edition: "1 of 1",
    tag: "Motion",
    year: "2025",
    img: "/nft4.webp",
    desc: `A 4K looping video work, 3 minutes and 17 seconds, depicting a single radio telescope dish in the Atacama Desert receiving a signal that — according to the embedded metadata — originates from coordinates outside the observable universe. RΛVΞN spent two years collaborating with astrophysicists, signal processing engineers, and a Jungian analyst to construct a work that operates on three simultaneous registers: scientific plausibility, psychological archetype, and pure aesthetic terror. The signal itself, when converted to audio, is included as a lossless WAV file in the token metadata. Several collectors have reported being unable to listen to it more than once.`,
    provenance: "Unique · 4K ProRes master · Atacama Desert, Chile · 2025",
  },
];

type NFT = (typeof NFTS)[number];

export default function NFTCollection() {
  const sectionRef = useRef<HTMLElement>(null);
  const [activeNFT, setActiveNFT] = useState<NFT | null>(null);
  const [modalVisible, setModalVisible] = useState(false);
  const modalRef = useRef<HTMLDivElement>(null);
  const modalContentRef = useRef<HTMLDivElement>(null);
  const imgOriginRef = useRef<DOMRect | null>(null);

  // ── Section entrance animations ──
  useEffect(() => {
    const section = sectionRef.current;
    if (!section) return;

    const ctx = gsap.context(() => {
      const titleEl = section.querySelector<HTMLElement>(".nft-title");
      const split = titleEl ? new SplitText(titleEl, { type: "chars" }) : null;
      if (split) gsap.set(split.chars, { yPercent: 115, opacity: 0 });

      gsap.set(section.querySelectorAll(".nft-row"), { opacity: 0, y: 24 });

      if (split) {
        gsap.to(split.chars, {
          yPercent: 0,
          opacity: 1,
          duration: 0.75,
          stagger: { amount: 0.4, from: "start" },
          ease: "power3.out",
          scrollTrigger: { trigger: section, start: "top 76%" },
        });
      }
      gsap.to(section.querySelectorAll(".nft-row"), {
        opacity: 1,
        y: 0,
        duration: 0.65,
        stagger: 0.1,
        ease: "power3.out",
        scrollTrigger: { trigger: section, start: "top 68%" },
      });
    }, section);

    return () => ctx.revert();
  }, []);

  // ── Open modal ──
  const openModal = useCallback((nft: NFT, thumbRect: DOMRect) => {
    imgOriginRef.current = thumbRect;
    setActiveNFT(nft);
    setModalVisible(true);
  }, []);

  // ── Animate modal in after mount ──
  useEffect(() => {
    if (!modalVisible || !modalRef.current || !modalContentRef.current) return;

    const modal = modalRef.current;
    const content = modalContentRef.current;
    const origin = imgOriginRef.current;

    // Lock body scroll
    document.body.style.overflow = "hidden";

    const tl = gsap.timeline();

    // Backdrop
    gsap.set(modal, { autoAlpha: 0 });
    tl.to(modal, { autoAlpha: 1, duration: 0.01 });

    // Curtain wipe
    const curtain = modal.querySelector<HTMLElement>(".nft-modal-curtain");
    gsap.set(curtain, { scaleY: 0, transformOrigin: "bottom center" });
    tl.to(curtain, { scaleY: 1, duration: 0.55, ease: "expo.inOut" }, 0);
    tl.to(
      curtain,
      {
        scaleY: 0,
        transformOrigin: "top center",
        duration: 0.45,
        ease: "expo.inOut",
      },
      0.5,
    );

    // Content slide up
    gsap.set(content, { y: 40, opacity: 0 });
    tl.to(
      content,
      { y: 0, opacity: 1, duration: 0.6, ease: "power3.out" },
      0.55,
    );

    // Image scale from thumb position
    const imgEl = modal.querySelector<HTMLElement>(".nft-modal-img-wrap");
    if (imgEl && origin) {
      const modalRect = imgEl.getBoundingClientRect();
      const scaleX = origin.width / modalRect.width;
      const scaleY = origin.height / modalRect.height;
      const dx =
        origin.left + origin.width / 2 - (modalRect.left + modalRect.width / 2);
      const dy =
        origin.top + origin.height / 2 - (modalRect.top + modalRect.height / 2);
      gsap.fromTo(
        imgEl,
        { x: dx, y: dy, scaleX, scaleY, opacity: 0 },
        {
          x: 0,
          y: 0,
          scaleX: 1,
          scaleY: 1,
          opacity: 1,
          duration: 0.75,
          ease: "expo.out",
        },
      );
    }

    // Stagger text lines
    const lines = modal.querySelectorAll<HTMLElement>(".nft-modal-animate");
    gsap.set(lines, { y: 18, opacity: 0 });
    tl.to(
      lines,
      { y: 0, opacity: 1, duration: 0.5, stagger: 0.06, ease: "power3.out" },
      0.65,
    );

    return () => {
      tl.kill();
    };
  }, [modalVisible]);

  // ── Close modal ──
  const closeModal = useCallback(() => {
    const modal = modalRef.current;
    const content = modalContentRef.current;
    if (!modal || !content) return;

    const tl = gsap.timeline({
      onComplete: () => {
        setModalVisible(false);
        setActiveNFT(null);
        document.body.style.overflow = "";
      },
    });
    tl.to(content, { y: 20, opacity: 0, duration: 0.35, ease: "power2.in" });
    tl.to(modal, { autoAlpha: 0, duration: 0.3, ease: "power2.in" }, "-=0.15");
  }, []);

  // ESC key
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (e.key === "Escape") closeModal();
    };
    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  }, [closeModal]);

  return (
    <>
      <section ref={sectionRef} id="nft-collection" className="nft-section">
        <div className="nft-line-v nft-line-left" />
        <div className="nft-line-v nft-line-right" />

        <div className="nft-inner">
          {/* Header */}
          <div className="nft-header" />

          {/* Title */}
          <div className="nft-title-wrap">
            <h2 className="nft-title">
              <span className="nft-title-clip">
                <span className="nft-title-solid">Selected</span>
              </span>
              <span className="nft-title-clip nft-title-clip--outline">
                <span className="nft-title-solid">Editions</span>
              </span>
            </h2>
          </div>

          {/* List */}
          <div className="nft-list" role="list">
            {NFTS.map((nft, i) => (
              <button
                key={nft.id}
                className="nft-row"
                role="listitem"
                aria-label={`View ${nft.title} by ${nft.artist}`}
                onClick={(e) => {
                  const thumb = (e.currentTarget as HTMLElement).querySelector(
                    ".nft-thumb-img-wrap",
                  );
                  const rect = thumb
                    ? thumb.getBoundingClientRect()
                    : (e.currentTarget as HTMLElement).getBoundingClientRect();
                  openModal(nft, rect);
                }}
              >
                {/* Index */}
                <span className="nft-row-id">{nft.id}</span>

                {/* Thumbnail */}
                <span className="nft-thumb">
                  <span className="nft-thumb-img-wrap">
                    <Image
                      src={nft.img}
                      alt={nft.title}
                      fill
                      sizes="80px"
                      className="nft-thumb-img"
                      loading="eager"
                    />
                  </span>
                </span>

                {/* Title + artist */}
                <span className="nft-row-info">
                  <span className="nft-row-title">{nft.title}</span>
                  <span className="nft-row-artist">{nft.artist}</span>
                </span>

                {/* Tag */}
                <span className="nft-row-tag">{nft.tag}</span>

                {/* Price */}
                <span className="nft-row-price-wrap">
                  <span className="nft-row-price">{nft.price}</span>
                </span>

                {/* Hover line */}
                <span className="nft-row-hover-line" aria-hidden="true" />
              </button>
            ))}
          </div>

          {/* Footer */}
          <div className="nft-footer">
            <div className="nft-footer-line" />
          </div>
        </div>
      </section>
      {modalVisible && activeNFT && (
        <div
          ref={modalRef}
          className="nft-modal"
          role="dialog"
          aria-modal="true"
          aria-label={activeNFT.title}
          onClick={(e) => {
            if (e.target === modalRef.current) closeModal();
          }}
        >
          {/* Curtain transition */}
          <div className="nft-modal-curtain" aria-hidden="true" />

          <div ref={modalContentRef} className="nft-modal-content">
            {/* Close */}
            <button
              className="nft-modal-close"
              onClick={closeModal}
              aria-label="Close"
            >
              <span className="nft-modal-close-inner">
                <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
                  <path
                    d="M1 1l12 12M13 1L1 13"
                    stroke="currentColor"
                    strokeWidth="1.3"
                    strokeLinecap="round"
                  />
                </svg>
              </span>
            </button>

            {/* Image */}
            <div className="nft-modal-img-wrap">
              <Image
                src={activeNFT.img}
                alt={activeNFT.title}
                width={350}
                height={350}
                className="nft-modal-img"
                priority
              />
            </div>

            {/* Info panel */}
            <div className="nft-modal-info">
              <div className="nft-modal-info-top">
                <span className="nft-modal-animate nft-modal-tag">
                  {activeNFT.tag}
                </span>
                <span className="nft-modal-animate nft-modal-year">
                  {activeNFT.year}
                </span>
              </div>

              <div className="nft-modal-title-wrap">
                <h2 className="nft-modal-animate nft-modal-title">
                  {activeNFT.title}
                </h2>
              </div>

              <p className="nft-modal-animate nft-modal-artist">
                {activeNFT.artist} ·{" "}
                <span className="nft-modal-edition">{activeNFT.edition}</span>
              </p>

              <div className="nft-modal-divider nft-modal-animate" />

              <p className="nft-modal-animate nft-modal-desc">
                {activeNFT.desc}
              </p>

              <p className="nft-modal-animate nft-modal-provenance">
                {activeNFT.provenance}
              </p>

              <div className="nft-modal-bid-row nft-modal-animate">
                <div className="nft-modal-price-wrap">
                  <span className="nft-modal-price-lbl">Current Bid</span>
                  <span className="nft-modal-price">{activeNFT.price}</span>
                </div>
                <button className="nft-modal-bid-btn">
                  <span className="nft-modal-bid-btn-inner">
                    Place Bid
                    <svg
                      width="11"
                      height="11"
                      viewBox="0 0 11 11"
                      fill="none"
                      aria-hidden="true"
                    >
                      <path
                        d="M1.5 5.5h8M6.5 2l3 3.5-3 3.5"
                        stroke="currentColor"
                        strokeWidth="1.2"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      />
                    </svg>
                  </span>
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
